### ISSUE TITLE
May I know how I can create a new fetechenv?

### ISSUE THREAD

**Issue by yatshunlee** [Farama-Foundation/Gym-Robotics#10]
Hello there. I'm new to gym and RL. I would like to know how to create a new fetchenv? Since I saw that the code in gym is no longer working anymore, like there is no more gym.make('FetchReach-v0').

**Comment by qgallouedec** [comment]
If your question is just about making the env, you just need to install `gym-robotics`:
```bash
pip install gym-robotics
```
and import `gym_robotics`:

```python
import gym
import gym_robotics

env = gym.make("FetchReach-v1")
```
