### ISSUE TITLE
[Question] How can I change the distance_threshold in fetch task?

### ISSUE THREAD

**Issue by undefinedcodezhong** [Farama-Foundation/Gym-Robotics#13]
### Question

I want to change the distance_threshold value to improve the difficulty of the fetch task.
Like handenv, I can use `env = gym.make('HandReach-v0',distance_threshold=0.001)`, but `env = gym.make('FetchReach-v1',distance_threshold=0.001)` doesn't work. 
Then I try to use `env.distance_threshold=0.001` to set the variable value, but the `compute_reward` function and the `info['is_success']` returned by `env.step` function seem to use the default distance_threshold 0.05. So what should I do if I want to change the distance_threshold in fetch task?

**Comment by qgallouedec** [comment]
Currently it is not possible to specify a custom `distance_threshold` with `gym.make`. If you really want to do it, you should install this repo from source 

```bash
git clone https://github.com/Farama-Foundation/Gym-Robotics
cd Gym-Robotics
pip install -e . # assuming you use pip
```

and go directly to the file `Gym-Robotics/gym_robotics/envs/fetch/reach.py` to change this line

https://github.com/Farama-Foundation/Gym-Robotics/blob/395d5aa1646ccddbc0196658dd78b03edcb9b3e0/gym_robotics/envs/fetch/reach.py#L28
