### ISSUE TITLE
[Bug Report] Gym 0.26 compatibility

### ISSUE THREAD

**Issue by vmoens** [Farama-Foundation/Gym-Robotics#17]
I believe this is not yet compatible with the latest gym (0.26.0) 

I tried the following code with and without `unwrapped`, but `render` consistently returns None.
```python
env = EnvCompatibility(gym.make("FetchReach-v1").unwrapped, render_mode="rgb_array")
```

Should we consider migrating to the new API if it's going to last?

**Comment by rodrigodelazcano** [comment]
#18 this PR makes the required changes.
